---
language: node_js

node_js:
  - stable

before_script:
  - npm -g install grunt-cli karma bower
  - bower install

script:
  - grunt

before_deploy:
  - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/gcloud.json
  - gcloud auth activate-service-account --key-file /tmp/gcloud.json
  - gsutil defacl ch -u AllUsers:R gs://$GCS_BUCKET

deploy:
  skip_cleanup: true
  provider: script
  script: gsutil -m rsync -d -r build/ gs://$GCS_BUCKET
  on:
    branch: master

after_deploy:
  - rm /tmp/gcloud.json
